version: "3.10"

services:
  web:
    build:
      context:  .
      dockerfile: Dockerfile
    command: python blog/manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - .env
      - .env.db
    depends_on:
      - db
    volumes:
      - ./blog:/app/blog

  db:
    image: postgres
    env_file:
      - .env.db
    healthcheck:
      test: pg_isready -U postgres
      timeout: 20s
      retries: 3
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
