[tool.poetry]
name = "blog-web-project"
version = "0.1.0"
description = ""
authors = ["Andrey Stoletov <stoletov314@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
django = ">=3.2.4"
django-environ = "^0.9.0"
setuptools = "^67.6.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
