[tool.poetry]
name = "blog-web-project"
version = "0.1.0"
description = ""
authors = ["Andrey Stoletov <stoletov314@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
django = ">=3.2.4"
setuptools = "^67.6.0"
psycopg2-binary = "^2.9.6"
pytest = "^7.3.1"
django-ckeditor = "^6.5.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
